### ISSUE TITLE
Uninstalling Mods

### ISSUE THREAD

**Issue by GoldDragon16** [Raicuparta/ow-mod-manager#104]
I was trying to uninstall my mods for Outer Wilds and I uninstalled my mod manager before uninstalling my mods and now when I try to reinstall the mod manager to uninstall my mods, it says 'installation aborted'. What do I do?

**Comment by Raicuparta** [comment]
Not sure what could be the problem with the installer. One thing you can do to uninstall all mods without the manager is doing the "verify files" in Steam or Epic. This will remove OWML, so mods won't load anymore.

**Comment by Raicuparta** [comment]
There is now a solution explained in the Readme for this problem: https://github.com/Raicuparta/ow-mod-manager#installation-aborted-error
