### ISSUE TITLE
Updating manager deletes OWML and all mods

### ISSUE THREAD

**Issue by misternebula** [Raicuparta/ow-mod-manager#118]

**Comment by Raicuparta** [comment]
More info: happens only if you install OWML in a sub-directory of the mod manager. So for anyone reading this: don't do that.

**Comment by Raicuparta** [comment]
1.2.3 shows a message if user tries to change OWML directory to sub-directory of Manager. Not a perfect solution since it's still possible to happen via other means, but good enough.
