### ISSUE TITLE
OW Mod Manager 1.2.3 doesn't install OWML

### ISSUE THREAD

**Issue by GanJJJJ** [Raicuparta/ow-mod-manager#124]
Hi.
- I installed Outer Wilds in Steam, launched game once 
- Downloaded OW Mod Manager and installed it (later uninstalled; and tried the same with Portable OWMM version - to no avail)
- Launched OW Mod Manager.
The problem is: 
1. for some reason OMWL doesn't respond to any clicks (I assume it's a "frontend problem"); version is "Not Avail...", 
2. "Install button" is highlighted, but isn't clickable at all
3. "three vertical dots" menue for OWML is clickable, but doesn't respond to "More info on GitHub" line. 

Please let me know how to fix it; I really want to play it in VR, but the Mod Manager just doesn't work. 
![image](https://user-images.githubusercontent.com/85820675/121798412-bf15d700-cc58-11eb-8de0-130ad3765466.png)
![image](https://user-images.githubusercontent.com/85820675/121798416-c806a880-cc58-11eb-84a3-d07351602bff.png)
![image](https://user-images.githubusercontent.com/85820675/121798419-d05ee380-cc58-11eb-9f16-f925c729bbef.png)

**Comment by GanJJJJ** [comment]
![image](https://user-images.githubusercontent.com/85820675/121798444-ff755500-cc58-11eb-982c-25e3802890b8.png)
Logs page is like this ^

**Comment by GanJJJJ** [comment]
... I installed OWML manually and added all the necessary mods, so for me it's not an issue anymore. 
But the OW Mod Manager is still not working (I just don't need it anymore), so the issue is open.

**Comment by Raicuparta** [comment]
This means the Mod Manager isn't able to fetch the info from the mod database. Maybe try resetting the mod manager settings (there's a reset button at the bottom in the settings tab). The portable version uses the same settings as the installed version, so maybe uninstalling wouldn't reset them.

The mod database is here, you can check if it's visible for you: https://raw.githubusercontent.com/Raicuparta/ow-mod-db/master/database.json

If you can see the database in the browser but not in the manager, something might be blocking the manager from making that request. Firewall or something like that.

**Comment by GanJJJJ** [comment]
> This means the Mod Manager isn't able to fetch the info from the mod database. Maybe try resetting the mod manager settings (there's a reset button at the bottom in the settings tab). The portable version uses the same settings as the installed version, so maybe uninstalling wouldn't reset them.
> 
> The mod database is here, you can check if it's visible for you: https://raw.githubusercontent.com/Raicuparta/ow-mod-db/master/database.json
> 
> If you can see the database in the browser but not in the manager, something might be blocking the manager from making that request. Firewall or something like that.

Thanks for a quick reply! Yep, probably some local region/country firewall lock or something. It would save me quite a lot of time if I'd try manual installation after failing the mod installation; but it's literally written there in the NomaiVR description page ;) 
As long as it works, no worries. 
Btw, the modification is insanely awesome! Have you tried contacting Outer WIlds developers so they would actually include your mode into the official package? I don't see why not, it just became a part of the Top-10-VR-Games-ever list. 
Thank you.

**Comment by Raicuparta** [comment]
@GanJJJJ I'm glad you liked it. But it would be really helpful for me if you could tell me if that database link opens for you. And maybe you could check the manager one more time to see if it magically works now? Otherwise I'll just try to show a better error message so other people aren't so confused.

**Comment by GanJJJJ** [comment]
>  it would be really helpful for me if you could tell me if that database link opens for you. And maybe you could check the manager one more time to see if it magically works now? Otherwise I'll just try to show a better error message so other people aren't so confused.

Installed Mod Manager once again. 
- Data base opens up in browser, I can see it: 
{
  "modManager": {
    "version": "v1.2.3", 
    ...etc
    
- Mod Manager is still "lagging" the same way as on screenshots above. 
Yeah, I think some pop-up message "data base is not loaded. Please check your firewall settings/ or try manual installation" would be extremely helpful.

**Comment by NelsVR** [comment]
hello I have the same issu but I try the manual installation but it doesnt work I have this

![Capture](https://user-images.githubusercontent.com/98233751/150652259-0de9ce70-228c-432e-babc-6b81c3f3de3c.PNG)
)

**Comment by NelsVR** [comment]
![Capture d’écran 2022-01-22 201419](https://user-images.githubusercontent.com/98233751/150652393-785943c8-9fc3-474d-b12a-73066a52edfe.jpg)

**Comment by Raicuparta** [comment]
@NelsVR looks like you're having issues due to the game pass version being protected. Make sure you follow all the instructions to install Outer Wilds in a user-accessible folder.

**Comment by NelsVR** [comment]
> @NelsVR looks like you're having issues due to the game pass version being protected. Make sure you follow all the instructions to install Outer Wilds in a user-accessible folder.

where can I find it? sorry I m bad :)

**Comment by Raicuparta** [comment]
@NelsVR Sorry didn't realize this wasn't about VR, so you probably didn't see this: https://outerwildsmods.com/mods/nomaivr/#xbox-app--game-pass-version
It's in the NomaiVR readme but it's the same for all mods.

**Comment by NelsVR** [comment]
oh thank you very much I try it and let you know

**Comment by NelsVR** [comment]
it's perfect thanks a lot you'r the king :)6
