### ISSUE TITLE
"OWML can't be in a sub-path of the Mod Manager" error

### ISSUE THREAD

**Issue by Goncorer** [Raicuparta/ow-mod-manager#125]
Whenever I try to launch the game through the launcher, this error message displays:
![image](https://user-images.githubusercontent.com/17153074/122847343-bbbbc480-d2c4-11eb-8d51-763b15deec99.png)
The game launches anyway, but some mods seem to not work properly.
The launcher installed OWML for me of course, and I haven't messed with any of the files since installing. How can I fix this? do I need to move the OWML folder, and if so, where?

Mod manager version 1.2.3
OWML version 1.1.8

This is the mods folder in AppData/roaming if it helps at all:
![image](https://user-images.githubusercontent.com/17153074/122847691-6c29c880-d2c5-11eb-958c-7f5a2cea453f.png)

**Comment by Raicuparta** [comment]
This shouldn't happen anymore
