### ISSUE TITLE
[OWML.Unity] : Font 'SpaceMono-Regular (UnityEngine.Font)' is not dynamic, which is required to override its style. Stack trace:

### ISSUE THREAD

**Issue by A9G-Data-Droid** [Raicuparta/ow-mod-manager#128]
I see this error repeated a lot:

> [OWML.Unity] : Font 'SpaceMono-Regular (UnityEngine.Font)' is not dynamic, which is required to override its style. Stack trace:

The mods are still running fine so I'm not sure what effect this exception has.

**Comment by Raicuparta** [comment]
Which nods are you using? This could be from a mod, from OWML, or from the base game.

**Comment by A9G-Data-Droid** [comment]
![image](https://user-images.githubusercontent.com/26984068/129626025-8e4c691e-cd4f-4934-ab55-9de1b7894e33.png)
