### ISSUE TITLE
Getting  "Failed - Virus detected" when attempting to download

### ISSUE THREAD

**Issue by NatashaGMT** [Raicuparta/ow-mod-manager#140]
I am wondering if this is a false positive or has the source been nobbled.

Downloading from https://outerwildsmods.com/mod-manager/
Using Chrome (Latest version) on Windows 10 (Fully up to date).
Security provided by Windows Defender.

Tested downloading in Firefox, this let the download complete. I then ran a quick scan on the file and it came up positive. Results are: 

Trojan:Win32/Spursint.Q!cl

Alert level: Severe
Status: Active
Date: 05/11/2021 03:39
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

Affected Items: file: C:\Users\natas\Downloads\OuterWildsModManager-Installer.exe

Edit:
This is looking more like a false positive by windows defender. I have ran this through Kaspersky threat intelligence portal (https://opentip.kaspersky.com/) and also Trend Micro Housecall (https://www.trendmicro.com/en_gb/forHome/products/housecall.html)and they have both come back clean.

**Comment by Raicuparta** [comment]
Looks like it's a common problem in this kind of electron app. Not much I can do about it, but maybe it goes away with an update. False positive.
