### ISSUE TITLE
Starting game with mod manager

### ISSUE THREAD

**Issue by wolfrat49** [Raicuparta/ow-mod-manager#149]
When i click the start game button, nothing happens apart from taking me to the log tab and displaying "Started console server on port (5 digits)". I suspect it's because my game is on another drive, the D Drive specifically, but I can't find any way to change where the mod manager is looking for the game. Thank you for your time in making this, even if I can't get it to work I appreciate what you do.

**Comment by Raicuparta** [comment]
Unfortunately OWML doesn't like being in a different drive than the game. They need to be installed in the same drive.

**Comment by someMinecrafter** [comment]
I have the same issue.
I have the game on Steam.
Moving OWML to the same directory as the Steam installation does not fix the issue.

**Comment by wolfrat49** [comment]
I was able to get it to work by using the portable version and installing the OWML mod that I think was discontinued in the normal manager. I saved it in the same directory as the game and it worked fine. Hope that helps anyone struggling, because this is really a great program.

**Comment by Onemario1234** [comment]
> Unfortunately OWML doesn't like being in a different drive than the game. They need to be installed in the same drive.

I have the same issue, and despite already doing this, the ModManager saves in the wrong drive anyway.
