### ISSUE TITLE
Request : Change the "Clear all logs" icon

### ISSUE THREAD

**Issue by Nolram12345** [Raicuparta/ow-mod-manager#153]
Yeah I have no clue why but I keep getting enraged by this icon.
![image](https://user-images.githubusercontent.com/37701550/156242086-4d72aeb5-1550-4975-a280-3a4fdbb0e24e.png)

Its almost invisible in the design and gives 0 indication of what it does. I would replace it with the delete icon from Material : 
![image](https://user-images.githubusercontent.com/37701550/156242393-96c8bc92-1447-448d-b76f-0e63ff89059c.png)

**Comment by Raicuparta** [comment]
That's actually the "clear all" icon from material, so don't blame me! I'm not sure if that bin is the best icon either though.

**Comment by Nolram12345** [comment]
I am well aware its the material icon. The problem is that the icon does the opposite of its purpose - it does not properly convey what it does. I had to _ask_ someone to find out that there even was a clear logs button... So maybe some other icon would work better ?
