### ISSUE TITLE
Mod Manager Game Path - Back Slash Being Replaced With Forward Slash

### ISSUE THREAD

**Issue by jeffsalisbury2022** [Raicuparta/ow-mod-manager#170]
The mod manager is unable to launch Outer Worlds because of the game path. I can use Find to navigate to the installation directory, or manually edit the directory, but when I launch the game the log shows it can't find the installation directory and in Settings I can see that the path has been modified where back slashes have been changed to forward slashes, which Windows does not like for file paths. For example:
    C:\Program Files (x86)\TheOuterWorlds
for the Game Folder after trying Start Game becomes this in Settings:
   C:/Program Files (x86)/TheOuterWorlds

I don't know of any way around this. I initially had the game installed in D:\Games\Epic\TheOuterWorlds and thought that might be the issue, but after removing and reinstalling to C:\Program Files (x86)\TheOuterWorlds I get the same behaviour. I have also just tried leaving the Game Path blank as the hover over text suggest it should auto-find the game, but when I try to save it displays an error related to the mkdir command "no such file or directory"

**Comment by Raicuparta** [comment]
You really mean The Outer Worlds? Because that's a different game. This is for Outer Wilds.

**Comment by MegaPiggy** [comment]
I love when this happens

**Comment by Raicuparta** [comment]
Well imma close this for now, @jeffsalisbury2022 if you just mispoke (several times) let me know and we can look into this.
