### ISSUE TITLE
Add mod images

### ISSUE THREAD

**Issue by amazingalek** [Raicuparta/ow-mod-manager#19]
Add image URL to manifest?

**Comment by amazingalek** [comment]
Images use much more vertical space. Expand mod to show image, or show image on all mods, and change the design to fit more vertical space per mod?

**Comment by amazingalek** [comment]
We'll go with the expansion approach. Image is preferably a screenshot, 1080p ish.

**Comment by Raicuparta** [comment]
Not gonna happen.
