### ISSUE TITLE
Close the mod loader when clicking "start game"

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/ow-mod-manager#52]
Electron being the thicc boi it is in regards to gobbling up all the RAM, it's probably a good idea.

**Comment by amazingalek** [comment]
🤔 is there any other way we can pack this (React) app without using Electron, without too much work? Googling it seems to suggests there are some other options we could look into: https://stackoverflow.com/questions/48152008/can-you-use-react-native-to-create-a-desktop-app

**Comment by Raicuparta** [comment]
I've looked into a few of them before we started this project, even started a bunch of test projects, and still preferred Electron. 

All other other frameworks are super unstable, unmaintained, or lack features. It's either this or drop JavaScript completely and go for something native.

That StackOverflow question is about React Native, which is a bit different from the React we use. Porting our code base to React Native wouldn't be copy/paste, would require a lot of rewriting.
